spring:
  application:
    name: "auth"
  datasource:
    url: ${DB_DATASOURCE_URL}
    password: ${DB_DATASOURCE_PASSWORD}
    username: ${DB_DATASOURCE_USERNAME}
  main:
    lazy-initialization: true
    allow-bean-definition-overriding: true
  cloud:
    config:
      enabled: false
  api-docs:
    path: ${API_DOCS_PATH}
  kafka:
    producer:
      bootstrap-servers: "localhost:9092"
      key-serializer: "org.apache.kafka.common.serialization.StringSerializer"
      value-serializer: "org.springframework.kafka.support.serializer.JsonSerializer"
    topic-auth:
      name: ${KAFKA_AUTH_TOPIC_NAME}
    topic-verify:
      name: ${KAFKA_VERIFY_TOPIC_NAME}
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: auth-app
            client-secret: 15po2NTE5e9AUEuv4CNkEvuRj2YEfq4Q
            authorization-grant-type: authorization_code
            scope:
              - openid
              - profile
              - email
        provider:
          keycloak:
            user-name-attribute: preferred_username
            issuer-uri: 'http://localhost:8080/realms/free-party'
            authorization-uri: 'http://localhost:8080/realms/free-party/protocol/openid-connect/auth'
            token-uri: 'http://localhost:8080/realms/free-party/protocol/openid-connect/token'
jpa:
   hibernate:
     ddl-auto: update
   properties:
     hibernate:
       dialect: org.hibernate.dialect.Postgresql
jwt:
  secret: ${JWT_SECRET}
  lifetime: ${JWT_LIFETIME}
refresh-authorization:
  lifetime: 28800000
server:
  port: 8090
verification:
  lifetime: 600000 #10 minutes