spring:
  application:
    name: "common"
  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect:org.hibernate.dialect.PostgreSQLDialect
