spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

  main:
    lazy-initialization: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: ${DIALECT}
        format_sql: true
  cloud:
    config:
      import-check:
        enabled: true
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${CLIENT_ID}
          #  client-secret: ${CLIENT_SECRET}
            authorization-grant-type: ${AUTHORIZATION_GRANT_TYPE}
            scope:
              - openid
              - profile
              - email
        provider:
          keycloak:
            user-name-attribute: ${USERNAME_ATTRIBUTE}
            issuer-uri: ${ISSUER_URI}
            jwk-set-uri: ${JWK_SET_URI}
            authorization-uri: ${AUTHORIZATION_URI}
            token-uri: ${TOKEN_URI}
logging:
  level:
    root: info
  file:
    name: public.log
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
server:
  port: 8092

keycloak:
  realm: ${REALM_NAME}
  server-url: ${SERVER_URL}
  client-id: ${CLIENT_ID}
  grant-type: ${GRANT_TYPE}
  username: ${USERNAME}
  password: ${PASSWORD}
  auth-login-url: ${TOKEN_URI}

