spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_URL}
    password: ${DATASOURCE_PASSWORD}
  main:
    lazy-initialization: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: ${DIALECT}
  cloud:
    config:
      import-check:
        enabled: true
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            authorization-grant-type: ${AUTHORIZATION_GRANT_TYPE}
            scope:
              - openid
              - profile
              - email
        provider:
          keycloak:
            user-name-attribute: ${USERNAME_ATTRIBUTE}
            issuer-uri: ${ISSUER_URI}
            authorization-uri: ${AUTHORIZATION_URI}
            jwk-set-uri: ${JWK_SET_URI}
            token-uri: ${TOKEN_URI}
logging:
  level:
    root: info
  file:
    name: public.log
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
server:
  port: 8092
